#! /bin/bash

if [ -n "$BASH_SOURCE" ]; then
	THIS_SCRIPT=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
	THIS_SCRIPT=$0
else
	THIS_SCRIPT="$(pwd)/pyrex-init-build-env"
fi

export PROJECT_ROOT=$(readlink -f $(dirname $THIS_SCRIPT))

if [ -z $PYREXCONFFILE ]; then
    PYREXCONFFILE=$PROJECT_ROOT/pyrex.ini
fi

OEROOT=$PROJECT_ROOT/poky
PYREX_CONFIG_BIND=$PROJECT_ROOT

export BB_ENV_EXTRAWHITE="\
    $BB_ENV_EXTRAWHITE \
    PROJECT_ROOT \
    "

. $PROJECT_ROOT/pyrex/pyrex-init-build-env

BUILD_DIR=$(pwd)

configure() {
    rm -f $BUILD_DIR/conf/site.conf
    if [ -e $PROJECT_ROOT/conf/site/$SITE.conf ]; then
        ln -sf $PROJECT_ROOT/conf/site/$SITE.conf $BUILD_DIR/conf/site.conf
    fi

    ln -sf $PROJECT_ROOT/conf/bblayers.conf $BUILD_DIR/conf/bblayers.conf
}

configure

